spring.application.name=piedraazul-agenda-service
server.port=8081

# BASE DE DATOS - MARIADB
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3307/piedraazul_agenda}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:piedraazul}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:piedraazul}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect


# SWAGGER / OPENAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.paths-to-match=/api/**


# MICROSERVICIO DE NOTIFICACIONES
notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8082}


# KEYCLOAK / JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8085/realms/PiedrAzul}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8085/realms/PiedrAzul/protocol/openid-connect/certs}

keycloak.token-uri=${KEYCLOAK_TOKEN_URI:http://localhost:8085/realms/PiedrAzul/protocol/openid-connect/token}
keycloak.client-id=${KEYCLOAK_CLIENT_ID:agenda-service}

keycloak.base-url=${KEYCLOAK_BASE_URL:http://localhost:8085}
keycloak.realm=${KEYCLOAK_REALM:PiedrAzul}
keycloak.admin-token-uri=${KEYCLOAK_ADMIN_TOKEN_URI:http://localhost:8085/realms/master/protocol/openid-connect/token}
keycloak.admin-username=${KEYCLOAK_ADMIN_USERNAME:admin}
keycloak.admin-password=${KEYCLOAK_ADMIN_PASSWORD:admin}

server.error.include-message=always
server.error.include-binding-errors=always
