spring.application.name=piedraazul-agenda-service
server.port=8081

# BASE DE DATOS - MARIADB DOCKER
spring.datasource.url=jdbc:mariadb://localhost:3307/piedraazul_agenda
spring.datasource.username=piedraazul
spring.datasource.password=piedraazul
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect


# SWAGGER / OPENAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.paths-to-match=/api/**

# MICROSERVICIO DE NOTIFICACIONES
notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8082}


# KEYCLOAK / JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8085/realms/PiedrAzul
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8085/realms/PiedrAzul/protocol/openid-connect/certs