SET SERVEROUTPUT ON;

BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_CITA_AUDITORIA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_HISTORIA_SOLO_CITA_ATENDIDA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_MEDICO_VALIDAR_INTERVALO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_PACIENTE_VALIDAR_FORMATOS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_CITA_VALIDAR_FECHA_HORA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE PKG_GESTION_PACIENTES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE PKG_GESTION_CITAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE PKG_GESTION_MEDICOS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE PKG_GESTION_MEDICAMENTOS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MEDICO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MEDICAMENTO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_RESUMEN_CITAS_PROFESIONAL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_CITA_FECHA_ESTADO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_PACIENTE_APELLIDOS_NOMBRES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PACIENTE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CITA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_AUDITORIA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HISTORIA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/


DECLARE
    V_INICIO NUMBER;
BEGIN
    SELECT NVL(MAX(ID_MEDICO),0) + 1 INTO V_INICIO FROM MEDICO_TERAPISTA;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_MEDICO START WITH ' || V_INICIO || ' INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/

DECLARE
    V_INICIO NUMBER;
BEGIN
    SELECT NVL(MAX(ID_MEDICAMENTO),0) + 1 INTO V_INICIO FROM MEDICAMENTO;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_MEDICAMENTO START WITH ' || V_INICIO || ' INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/

/* ============================================================================
   j) GENERACION DE SECUENCIAS - MINIMO 2
   Se crean 4 para manejar llaves primarias sin escribir IDs manualmente.
============================================================================ */
DECLARE
    V_INICIO NUMBER;
BEGIN
    SELECT NVL(MAX(ID_PACIENTE),0) + 1 INTO V_INICIO FROM PACIENTE;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_PACIENTE START WITH ' || V_INICIO || ' INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/

DECLARE
    V_INICIO NUMBER;
BEGIN
    SELECT NVL(MAX(ID_CITA),0) + 1 INTO V_INICIO FROM CITA;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_CITA START WITH ' || V_INICIO || ' INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/

DECLARE
    V_INICIO NUMBER;
BEGIN
    SELECT NVL(MAX(ID_AUDITORIA),0) + 1 INTO V_INICIO FROM AUDITORIA;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_AUDITORIA START WITH ' || V_INICIO || ' INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/

DECLARE
    V_INICIO NUMBER;
BEGIN
    SELECT NVL(MAX(ID_HISTORIA),0) + 1 INTO V_INICIO FROM HISTORIA_CLINICA;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_HISTORIA START WITH ' || V_INICIO || ' INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/

/* ============================================================================
      j) Indices y secuencias: 2 indices propios y 6 secuencias:
      SEQ_PACIENTE, SEQ_CITA, SEQ_AUDITORIA, SEQ_HISTORIA,
      SEQ_MEDICO y SEQ_MEDICAMENTO.
============================================================================ */

/* Justificacion:
   Este indice mejora consultas frecuentes de agenda donde se filtran citas
   por fecha y estado, por ejemplo: citas programadas de un dia especifico. */
CREATE INDEX IDX_CITA_FECHA_ESTADO
ON CITA(FECHA_CITA, ESTADO);

/* Justificacion:
   Este indice mejora busquedas y ordenamientos de pacientes por apellidos
   y nombres, caso comun en admision/agendamiento. */
CREATE INDEX IDX_PACIENTE_APELLIDOS_NOMBRES
ON PACIENTE(APELLIDOS, NOMBRES);

/* ============================================================================
   h) CREACION Y GENERACION DE VISTA - 1 VISTA
============================================================================ */
CREATE OR REPLACE VIEW VW_RESUMEN_CITAS_PROFESIONAL AS
SELECT
    M.ID_MEDICO,
    M.NOMBRES || ' ' || M.APELLIDOS AS PROFESIONAL,
    M.TIPO_PROFESIONAL,
    COUNT(C.ID_CITA) AS TOTAL_CITAS,
    SUM(CASE WHEN C.ESTADO = 'PROGRAMADA' THEN 1 ELSE 0 END) AS CITAS_PROGRAMADAS,
    SUM(CASE WHEN C.ESTADO = 'ATENDIDA' THEN 1 ELSE 0 END) AS CITAS_ATENDIDAS,
    SUM(CASE WHEN C.ESTADO = 'CANCELADA' THEN 1 ELSE 0 END) AS CITAS_CANCELADAS,
    SUM(CASE WHEN C.ESTADO = 'REPROGRAMADA' THEN 1 ELSE 0 END) AS CITAS_REPROGRAMADAS
FROM MEDICO_TERAPISTA M
LEFT JOIN CITA C ON C.ID_MEDICO = M.ID_MEDICO
GROUP BY M.ID_MEDICO, M.NOMBRES, M.APELLIDOS, M.TIPO_PROFESIONAL;
/

/* ============================================================================
      b) 4 paquetes CRUD:
      PKG_GESTION_PACIENTES,
      PKG_GESTION_CITAS,
      PKG_GESTION_MEDICOS,
      PKG_GESTION_MEDICAMENTOS.
      Cada paquete contiene insertar, actualizar, consultar y eliminar/inactivar.
   d) MANEJO DE EXCEPCIONES - se usan excepciones propias y del sistema.
   f) TIPO COMPUESTO RECORD - t_paciente_rec.
============================================================================ */
CREATE OR REPLACE PACKAGE PKG_GESTION_PACIENTES AS

    TYPE T_PACIENTE_REC IS RECORD (
        ID_PACIENTE      PACIENTE.ID_PACIENTE%TYPE,
        TIPO_DOCUMENTO   PACIENTE.TIPO_DOCUMENTO%TYPE,
        NUM_DOCUMENTO    PACIENTE.NUM_DOCUMENTO%TYPE,
        NOMBRES          PACIENTE.NOMBRES%TYPE,
        APELLIDOS        PACIENTE.APELLIDOS%TYPE,
        FECHA_NACIMIENTO PACIENTE.FECHA_NACIMIENTO%TYPE,
        CELULAR          PACIENTE.CELULAR%TYPE,
        DIRECCION        PACIENTE.DIRECCION%TYPE,
        EMAIL            PACIENTE.EMAIL%TYPE,
        ESTADO           PACIENTE.ESTADO%TYPE
    );

    PROCEDURE INSERTAR_PACIENTE(
        P_TIPO_DOCUMENTO   IN PACIENTE.TIPO_DOCUMENTO%TYPE,
        P_NUM_DOCUMENTO    IN PACIENTE.NUM_DOCUMENTO%TYPE,
        P_NOMBRES          IN PACIENTE.NOMBRES%TYPE,
        P_APELLIDOS        IN PACIENTE.APELLIDOS%TYPE,
        P_FECHA_NACIMIENTO IN PACIENTE.FECHA_NACIMIENTO%TYPE,
        P_CELULAR          IN PACIENTE.CELULAR%TYPE,
        P_DIRECCION        IN PACIENTE.DIRECCION%TYPE,
        P_EMAIL            IN PACIENTE.EMAIL%TYPE,
        P_ID_GENERADO      OUT PACIENTE.ID_PACIENTE%TYPE
    );

    PROCEDURE ACTUALIZAR_PACIENTE(
        P_ID_PACIENTE      IN PACIENTE.ID_PACIENTE%TYPE,
        P_CELULAR          IN PACIENTE.CELULAR%TYPE,
        P_DIRECCION        IN PACIENTE.DIRECCION%TYPE,
        P_EMAIL            IN PACIENTE.EMAIL%TYPE
    );

    PROCEDURE CONSULTAR_PACIENTE(
        P_ID_PACIENTE IN PACIENTE.ID_PACIENTE%TYPE,
        P_PACIENTE    OUT T_PACIENTE_REC
    );

    PROCEDURE ELIMINAR_PACIENTE(
        P_ID_PACIENTE IN PACIENTE.ID_PACIENTE%TYPE
    );

    FUNCTION EXISTE_PACIENTE(
        P_NUM_DOCUMENTO IN PACIENTE.NUM_DOCUMENTO%TYPE
    ) RETURN BOOLEAN;

END PKG_GESTION_PACIENTES;
/

CREATE OR REPLACE PACKAGE BODY PKG_GESTION_PACIENTES AS

    E_PACIENTE_NO_EXISTE EXCEPTION;
    E_EMAIL_INVALIDO     EXCEPTION;

    PROCEDURE INSERTAR_PACIENTE(
        P_TIPO_DOCUMENTO   IN PACIENTE.TIPO_DOCUMENTO%TYPE,
        P_NUM_DOCUMENTO    IN PACIENTE.NUM_DOCUMENTO%TYPE,
        P_NOMBRES          IN PACIENTE.NOMBRES%TYPE,
        P_APELLIDOS        IN PACIENTE.APELLIDOS%TYPE,
        P_FECHA_NACIMIENTO IN PACIENTE.FECHA_NACIMIENTO%TYPE,
        P_CELULAR          IN PACIENTE.CELULAR%TYPE,
        P_DIRECCION        IN PACIENTE.DIRECCION%TYPE,
        P_EMAIL            IN PACIENTE.EMAIL%TYPE,
        P_ID_GENERADO      OUT PACIENTE.ID_PACIENTE%TYPE
    ) IS
    BEGIN
        IF P_EMAIL IS NOT NULL AND NOT REGEXP_LIKE(P_EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
            RAISE E_EMAIL_INVALIDO;
        END IF;

        P_ID_GENERADO := SEQ_PACIENTE.NEXTVAL;

        INSERT INTO PACIENTE(
            ID_PACIENTE, TIPO_DOCUMENTO, NUM_DOCUMENTO, NOMBRES, APELLIDOS,
            FECHA_NACIMIENTO, CELULAR, DIRECCION, EMAIL, ESTADO
        ) VALUES (
            P_ID_GENERADO, UPPER(P_TIPO_DOCUMENTO), P_NUM_DOCUMENTO,
            INITCAP(P_NOMBRES), INITCAP(P_APELLIDOS), P_FECHA_NACIMIENTO,
            P_CELULAR, P_DIRECCION, LOWER(P_EMAIL), 'A'
        );

        DBMS_OUTPUT.PUT_LINE('Paciente insertado con ID: ' || P_ID_GENERADO);

    EXCEPTION
        WHEN E_EMAIL_INVALIDO THEN
            RAISE_APPLICATION_ERROR(-20001, 'El correo del paciente no tiene un formato valido.');
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20002, 'Ya existe un paciente con ese numero de documento.');
        WHEN VALUE_ERROR THEN
            RAISE_APPLICATION_ERROR(-20003, 'Error de tipo o longitud en los datos del paciente.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20004, 'Error inesperado al insertar paciente: ' || SQLERRM);
    END INSERTAR_PACIENTE;

    PROCEDURE ACTUALIZAR_PACIENTE(
        P_ID_PACIENTE      IN PACIENTE.ID_PACIENTE%TYPE,
        P_CELULAR          IN PACIENTE.CELULAR%TYPE,
        P_DIRECCION        IN PACIENTE.DIRECCION%TYPE,
        P_EMAIL            IN PACIENTE.EMAIL%TYPE
    ) IS
        V_TOTAL NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_TOTAL
        FROM PACIENTE
        WHERE ID_PACIENTE = P_ID_PACIENTE;

        IF V_TOTAL = 0 THEN
            RAISE E_PACIENTE_NO_EXISTE;
        END IF;

        IF P_EMAIL IS NOT NULL AND NOT REGEXP_LIKE(P_EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
            RAISE E_EMAIL_INVALIDO;
        END IF;

        UPDATE PACIENTE
        SET CELULAR = P_CELULAR,
            DIRECCION = P_DIRECCION,
            EMAIL = LOWER(P_EMAIL)
        WHERE ID_PACIENTE = P_ID_PACIENTE;

        DBMS_OUTPUT.PUT_LINE('Paciente actualizado: ' || P_ID_PACIENTE);

    EXCEPTION
        WHEN E_PACIENTE_NO_EXISTE THEN
            RAISE_APPLICATION_ERROR(-20005, 'No existe el paciente que se desea actualizar.');
        WHEN E_EMAIL_INVALIDO THEN
            RAISE_APPLICATION_ERROR(-20006, 'El correo actualizado no tiene un formato valido.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20007, 'Error inesperado al actualizar paciente: ' || SQLERRM);
    END ACTUALIZAR_PACIENTE;

    PROCEDURE CONSULTAR_PACIENTE(
        P_ID_PACIENTE IN PACIENTE.ID_PACIENTE%TYPE,
        P_PACIENTE    OUT T_PACIENTE_REC
    ) IS
    BEGIN
        SELECT ID_PACIENTE, TIPO_DOCUMENTO, NUM_DOCUMENTO, NOMBRES, APELLIDOS,
               FECHA_NACIMIENTO, CELULAR, DIRECCION, EMAIL, ESTADO
        INTO P_PACIENTE
        FROM PACIENTE
        WHERE ID_PACIENTE = P_ID_PACIENTE;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20008, 'No existe el paciente consultado.');
        WHEN TOO_MANY_ROWS THEN
            RAISE_APPLICATION_ERROR(-20009, 'La consulta retorno mas de un paciente.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20010, 'Error inesperado al consultar paciente: ' || SQLERRM);
    END CONSULTAR_PACIENTE;

    PROCEDURE ELIMINAR_PACIENTE(
        P_ID_PACIENTE IN PACIENTE.ID_PACIENTE%TYPE
    ) IS
        V_TOTAL NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_TOTAL
        FROM PACIENTE
        WHERE ID_PACIENTE = P_ID_PACIENTE;

        IF V_TOTAL = 0 THEN
            RAISE E_PACIENTE_NO_EXISTE;
        END IF;

        /* Eliminacion logica para no romper citas historicas. */
        UPDATE PACIENTE
        SET ESTADO = 'I'
        WHERE ID_PACIENTE = P_ID_PACIENTE;

        DBMS_OUTPUT.PUT_LINE('Paciente inactivado: ' || P_ID_PACIENTE);

    EXCEPTION
        WHEN E_PACIENTE_NO_EXISTE THEN
            RAISE_APPLICATION_ERROR(-20011, 'No existe el paciente que se desea eliminar/inactivar.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20012, 'Error inesperado al eliminar paciente: ' || SQLERRM);
    END ELIMINAR_PACIENTE;

    FUNCTION EXISTE_PACIENTE(
        P_NUM_DOCUMENTO IN PACIENTE.NUM_DOCUMENTO%TYPE
    ) RETURN BOOLEAN IS
        V_TOTAL NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_TOTAL
        FROM PACIENTE
        WHERE NUM_DOCUMENTO = P_NUM_DOCUMENTO;

        RETURN V_TOTAL > 0;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN FALSE;
    END EXISTE_PACIENTE;

END PKG_GESTION_PACIENTES;
/

/* ============================================================================
   b) SEGUNDO PAQUETE CRUD - CITAS
   d) MANEJO DE EXCEPCIONES
============================================================================ */
CREATE OR REPLACE PACKAGE PKG_GESTION_CITAS AS

    TYPE T_CITA_REC IS RECORD (
        ID_CITA        CITA.ID_CITA%TYPE,
        ID_PACIENTE    CITA.ID_PACIENTE%TYPE,
        ID_MEDICO      CITA.ID_MEDICO%TYPE,
        FECHA_CITA     CITA.FECHA_CITA%TYPE,
        HORA_CITA      CITA.HORA_CITA%TYPE,
        ESTADO         CITA.ESTADO%TYPE,
        MOTIVO         CITA.MOTIVO%TYPE,
        OBSERVACIONES  CITA.OBSERVACIONES%TYPE,
        FECHA_REGISTRO CITA.FECHA_REGISTRO%TYPE
    );

    PROCEDURE INSERTAR_CITA(
        P_ID_PACIENTE   IN CITA.ID_PACIENTE%TYPE,
        P_ID_MEDICO     IN CITA.ID_MEDICO%TYPE,
        P_FECHA_CITA    IN CITA.FECHA_CITA%TYPE,
        P_HORA_CITA     IN CITA.HORA_CITA%TYPE,
        P_MOTIVO        IN CITA.MOTIVO%TYPE,
        P_OBSERVACIONES IN CITA.OBSERVACIONES%TYPE,
        P_ID_GENERADO   OUT CITA.ID_CITA%TYPE
    );

    PROCEDURE ACTUALIZAR_CITA(
        P_ID_CITA       IN CITA.ID_CITA%TYPE,
        P_ID_MEDICO     IN CITA.ID_MEDICO%TYPE,
        P_FECHA_CITA    IN CITA.FECHA_CITA%TYPE,
        P_HORA_CITA     IN CITA.HORA_CITA%TYPE,
        P_ESTADO        IN CITA.ESTADO%TYPE,
        P_MOTIVO        IN CITA.MOTIVO%TYPE,
        P_OBSERVACIONES IN CITA.OBSERVACIONES%TYPE
    );

    PROCEDURE ACTUALIZAR_ESTADO_CITA(
        P_ID_CITA IN CITA.ID_CITA%TYPE,
        P_ESTADO  IN CITA.ESTADO%TYPE
    );

    PROCEDURE CONSULTAR_CITA(
        P_ID_CITA IN CITA.ID_CITA%TYPE,
        P_CITA    OUT T_CITA_REC
    );

    PROCEDURE ELIMINAR_CITA(
        P_ID_CITA IN CITA.ID_CITA%TYPE
    );

    FUNCTION EXISTE_CITA(
        P_ID_CITA IN CITA.ID_CITA%TYPE
    ) RETURN BOOLEAN;

END PKG_GESTION_CITAS;
/

CREATE OR REPLACE PACKAGE BODY PKG_GESTION_CITAS AS

    E_CITA_NO_EXISTE      EXCEPTION;
    E_PACIENTE_NO_EXISTE  EXCEPTION;
    E_MEDICO_NO_EXISTE    EXCEPTION;
    E_ESTADO_INVALIDO     EXCEPTION;
    E_HORA_INVALIDA       EXCEPTION;
    E_FECHA_INVALIDA      EXCEPTION;

    PROCEDURE VALIDAR_ESTADO(
        P_ESTADO IN CITA.ESTADO%TYPE
    ) IS
    BEGIN
        IF UPPER(P_ESTADO) NOT IN ('PROGRAMADA', 'ATENDIDA', 'CANCELADA', 'REPROGRAMADA') THEN
            RAISE E_ESTADO_INVALIDO;
        END IF;
    END VALIDAR_ESTADO;

    PROCEDURE VALIDAR_HORA(
        P_HORA IN CITA.HORA_CITA%TYPE
    ) IS
    BEGIN
        IF NOT REGEXP_LIKE(P_HORA, '^([01][0-9]|2[0-3]):[0-5][0-9]$') THEN
            RAISE E_HORA_INVALIDA;
        END IF;
    END VALIDAR_HORA;

    PROCEDURE VALIDAR_PACIENTE(
        P_ID_PACIENTE IN CITA.ID_PACIENTE%TYPE
    ) IS
        V_TOTAL NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_TOTAL
        FROM PACIENTE
        WHERE ID_PACIENTE = P_ID_PACIENTE
          AND ESTADO = 'A';

        IF V_TOTAL = 0 THEN
            RAISE E_PACIENTE_NO_EXISTE;
        END IF;
    END VALIDAR_PACIENTE;

    PROCEDURE VALIDAR_MEDICO(
        P_ID_MEDICO IN CITA.ID_MEDICO%TYPE
    ) IS
        V_TOTAL NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_TOTAL
        FROM MEDICO_TERAPISTA
        WHERE ID_MEDICO = P_ID_MEDICO
          AND ESTADO = 'A';

        IF V_TOTAL = 0 THEN
            RAISE E_MEDICO_NO_EXISTE;
        END IF;
    END VALIDAR_MEDICO;

    PROCEDURE INSERTAR_CITA(
        P_ID_PACIENTE   IN CITA.ID_PACIENTE%TYPE,
        P_ID_MEDICO     IN CITA.ID_MEDICO%TYPE,
        P_FECHA_CITA    IN CITA.FECHA_CITA%TYPE,
        P_HORA_CITA     IN CITA.HORA_CITA%TYPE,
        P_MOTIVO        IN CITA.MOTIVO%TYPE,
        P_OBSERVACIONES IN CITA.OBSERVACIONES%TYPE,
        P_ID_GENERADO   OUT CITA.ID_CITA%TYPE
    ) IS
    BEGIN
        IF P_FECHA_CITA < TRUNC(SYSDATE) THEN
            RAISE E_FECHA_INVALIDA;
        END IF;

        VALIDAR_HORA(P_HORA_CITA);
        VALIDAR_PACIENTE(P_ID_PACIENTE);
        VALIDAR_MEDICO(P_ID_MEDICO);

        P_ID_GENERADO := SEQ_CITA.NEXTVAL;

        INSERT INTO CITA(
            ID_CITA,
            ID_PACIENTE,
            ID_MEDICO,
            FECHA_CITA,
            HORA_CITA,
            ESTADO,
            MOTIVO,
            OBSERVACIONES,
            FECHA_REGISTRO
        ) VALUES (
            P_ID_GENERADO,
            P_ID_PACIENTE,
            P_ID_MEDICO,
            P_FECHA_CITA,
            P_HORA_CITA,
            'PROGRAMADA',
            INITCAP(P_MOTIVO),
            P_OBSERVACIONES,
            SYSDATE
        );

        DBMS_OUTPUT.PUT_LINE('Cita insertada correctamente con ID: ' || P_ID_GENERADO);

    EXCEPTION
        WHEN E_FECHA_INVALIDA THEN
            RAISE_APPLICATION_ERROR(-20201, 'No se puede crear una cita en una fecha pasada.');
        WHEN E_HORA_INVALIDA THEN
            RAISE_APPLICATION_ERROR(-20202, 'La hora debe tener formato HH24:MI. Ejemplo: 08:30.');
        WHEN E_PACIENTE_NO_EXISTE THEN
            RAISE_APPLICATION_ERROR(-20203, 'No existe un paciente activo con el ID indicado.');
        WHEN E_MEDICO_NO_EXISTE THEN
            RAISE_APPLICATION_ERROR(-20204, 'No existe un medico/terapista activo con el ID indicado.');
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20205, 'Ya existe una cita para ese medico en la misma fecha y hora.');
        WHEN VALUE_ERROR THEN
            RAISE_APPLICATION_ERROR(-20206, 'Error de tipo o longitud en los datos de la cita.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20207, 'Error inesperado al insertar cita: ' || SQLERRM);
    END INSERTAR_CITA;

    PROCEDURE ACTUALIZAR_CITA(
        P_ID_CITA       IN CITA.ID_CITA%TYPE,
        P_ID_MEDICO     IN CITA.ID_MEDICO%TYPE,
        P_FECHA_CITA    IN CITA.FECHA_CITA%TYPE,
        P_HORA_CITA     IN CITA.HORA_CITA%TYPE,
        P_ESTADO        IN CITA.ESTADO%TYPE,
        P_MOTIVO        IN CITA.MOTIVO%TYPE,
        P_OBSERVACIONES IN CITA.OBSERVACIONES%TYPE
    ) IS
        V_TOTAL NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_TOTAL
        FROM CITA
        WHERE ID_CITA = P_ID_CITA;

        IF V_TOTAL = 0 THEN
            RAISE E_CITA_NO_EXISTE;
        END IF;

        IF P_FECHA_CITA < TRUNC(SYSDATE) AND UPPER(P_ESTADO) IN ('PROGRAMADA', 'REPROGRAMADA') THEN
            RAISE E_FECHA_INVALIDA;
        END IF;

        VALIDAR_HORA(P_HORA_CITA);
        VALIDAR_ESTADO(P_ESTADO);
        VALIDAR_MEDICO(P_ID_MEDICO);

        UPDATE CITA
        SET ID_MEDICO = P_ID_MEDICO,
            FECHA_CITA = P_FECHA_CITA,
            HORA_CITA = P_HORA_CITA,
            ESTADO = UPPER(P_ESTADO),
            MOTIVO = INITCAP(P_MOTIVO),
            OBSERVACIONES = P_OBSERVACIONES
        WHERE ID_CITA = P_ID_CITA;

        DBMS_OUTPUT.PUT_LINE('Cita actualizada correctamente: ' || P_ID_CITA);

    EXCEPTION
        WHEN E_CITA_NO_EXISTE THEN
            RAISE_APPLICATION_ERROR(-20208, 'No existe la cita que se desea actualizar.');
        WHEN E_FECHA_INVALIDA THEN
            RAISE_APPLICATION_ERROR(-20209, 'No se puede programar o reprogramar una cita en una fecha pasada.');
        WHEN E_HORA_INVALIDA THEN
            RAISE_APPLICATION_ERROR(-20210, 'La hora actualizada debe tener formato HH24:MI.');
        WHEN E_ESTADO_INVALIDO THEN
            RAISE_APPLICATION_ERROR(-20211, 'Estado invalido para la cita.');
        WHEN E_MEDICO_NO_EXISTE THEN
            RAISE_APPLICATION_ERROR(-20212, 'No existe un medico/terapista activo con el ID indicado.');
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20213, 'Ya existe otra cita para ese medico en la misma fecha y hora.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20214, 'Error inesperado al actualizar cita: ' || SQLERRM);
    END ACTUALIZAR_CITA;

    PROCEDURE ACTUALIZAR_ESTADO_CITA(
        P_ID_CITA IN CITA.ID_CITA%TYPE,
        P_ESTADO  IN CITA.ESTADO%TYPE
    ) IS
        V_TOTAL NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_TOTAL
        FROM CITA
        WHERE ID_CITA = P_ID_CITA;

        IF V_TOTAL = 0 THEN
            RAISE E_CITA_NO_EXISTE;
        END IF;

        VALIDAR_ESTADO(P_ESTADO);

        UPDATE CITA
        SET ESTADO = UPPER(P_ESTADO)
        WHERE ID_CITA = P_ID_CITA;

        DBMS_OUTPUT.PUT_LINE('Estado actualizado para la cita: ' || P_ID_CITA);

    EXCEPTION
        WHEN E_CITA_NO_EXISTE THEN
            RAISE_APPLICATION_ERROR(-20215, 'No existe la cita que se desea actualizar.');
        WHEN E_ESTADO_INVALIDO THEN
            RAISE_APPLICATION_ERROR(-20216, 'Estado invalido para la cita.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20217, 'Error inesperado al actualizar estado de cita: ' || SQLERRM);
    END ACTUALIZAR_ESTADO_CITA;

    PROCEDURE CONSULTAR_CITA(
        P_ID_CITA IN CITA.ID_CITA%TYPE,
        P_CITA    OUT T_CITA_REC
    ) IS
    BEGIN
        SELECT
            ID_CITA,
            ID_PACIENTE,
            ID_MEDICO,
            FECHA_CITA,
            HORA_CITA,
            ESTADO,
            MOTIVO,
            OBSERVACIONES,
            FECHA_REGISTRO
        INTO P_CITA
        FROM CITA
        WHERE ID_CITA = P_ID_CITA;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20218, 'No existe la cita consultada.');
        WHEN TOO_MANY_ROWS THEN
            RAISE_APPLICATION_ERROR(-20219, 'La consulta retorno mas de una cita.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20220, 'Error inesperado al consultar cita: ' || SQLERRM);
    END CONSULTAR_CITA;

    PROCEDURE ELIMINAR_CITA(
        P_ID_CITA IN CITA.ID_CITA%TYPE
    ) IS
        V_TOTAL NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_TOTAL
        FROM CITA
        WHERE ID_CITA = P_ID_CITA;

        IF V_TOTAL = 0 THEN
            RAISE E_CITA_NO_EXISTE;
        END IF;

        /* Eliminacion logica: la cita se cancela para conservar trazabilidad. */
        UPDATE CITA
        SET ESTADO = 'CANCELADA',
            OBSERVACIONES = NVL(OBSERVACIONES, '') || ' | Cita cancelada por eliminacion logica.'
        WHERE ID_CITA = P_ID_CITA;

        DBMS_OUTPUT.PUT_LINE('Cita eliminada logicamente/cancelada: ' || P_ID_CITA);

    EXCEPTION
        WHEN E_CITA_NO_EXISTE THEN
            RAISE_APPLICATION_ERROR(-20221, 'No existe la cita que se desea eliminar/cancelar.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20222, 'Error inesperado al eliminar cita: ' || SQLERRM);
    END ELIMINAR_CITA;

    FUNCTION EXISTE_CITA(
        P_ID_CITA IN CITA.ID_CITA%TYPE
    ) RETURN BOOLEAN IS
        V_TOTAL NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_TOTAL
        FROM CITA
        WHERE ID_CITA = P_ID_CITA;

        RETURN V_TOTAL > 0;

    EXCEPTION
        WHEN OTHERS THEN
            RETURN FALSE;
    END EXISTE_CITA;

END PKG_GESTION_CITAS;
/

/* ============================================================================
   b) TERCER PAQUETE CRUD - MEDICOS/TERAPISTAS
   d) MANEJO DE EXCEPCIONES
============================================================================ */
CREATE OR REPLACE PACKAGE PKG_GESTION_MEDICOS AS

    TYPE T_MEDICO_REC IS RECORD (
        ID_MEDICO         MEDICO_TERAPISTA.ID_MEDICO%TYPE,
        TIPO_DOCUMENTO    MEDICO_TERAPISTA.TIPO_DOCUMENTO%TYPE,
        NUM_DOCUMENTO     MEDICO_TERAPISTA.NUM_DOCUMENTO%TYPE,
        NOMBRES           MEDICO_TERAPISTA.NOMBRES%TYPE,
        APELLIDOS         MEDICO_TERAPISTA.APELLIDOS%TYPE,
        TIPO_PROFESIONAL  MEDICO_TERAPISTA.TIPO_PROFESIONAL%TYPE,
        INTERVALO_MINUTOS MEDICO_TERAPISTA.INTERVALO_MINUTOS%TYPE,
        TELEFONO          MEDICO_TERAPISTA.TELEFONO%TYPE,
        EMAIL             MEDICO_TERAPISTA.EMAIL%TYPE,
        ESTADO            MEDICO_TERAPISTA.ESTADO%TYPE
    );

    PROCEDURE INSERTAR_MEDICO(
        P_TIPO_DOCUMENTO    IN MEDICO_TERAPISTA.TIPO_DOCUMENTO%TYPE,
        P_NUM_DOCUMENTO     IN MEDICO_TERAPISTA.NUM_DOCUMENTO%TYPE,
        P_NOMBRES           IN MEDICO_TERAPISTA.NOMBRES%TYPE,
        P_APELLIDOS         IN MEDICO_TERAPISTA.APELLIDOS%TYPE,
        P_TIPO_PROFESIONAL  IN MEDICO_TERAPISTA.TIPO_PROFESIONAL%TYPE,
        P_INTERVALO_MINUTOS IN MEDICO_TERAPISTA.INTERVALO_MINUTOS%TYPE,
        P_TELEFONO          IN MEDICO_TERAPISTA.TELEFONO%TYPE,
        P_EMAIL             IN MEDICO_TERAPISTA.EMAIL%TYPE,
        P_ID_GENERADO       OUT MEDICO_TERAPISTA.ID_MEDICO%TYPE
    );

    PROCEDURE ACTUALIZAR_MEDICO(
        P_ID_MEDICO         IN MEDICO_TERAPISTA.ID_MEDICO%TYPE,
        P_TELEFONO          IN MEDICO_TERAPISTA.TELEFONO%TYPE,
        P_EMAIL             IN MEDICO_TERAPISTA.EMAIL%TYPE,
        P_INTERVALO_MINUTOS IN MEDICO_TERAPISTA.INTERVALO_MINUTOS%TYPE
    );

    PROCEDURE CONSULTAR_MEDICO(
        P_ID_MEDICO IN MEDICO_TERAPISTA.ID_MEDICO%TYPE,
        P_MEDICO    OUT T_MEDICO_REC
    );

    PROCEDURE ELIMINAR_MEDICO(
        P_ID_MEDICO IN MEDICO_TERAPISTA.ID_MEDICO%TYPE
    );

    FUNCTION EXISTE_MEDICO(
        P_NUM_DOCUMENTO IN MEDICO_TERAPISTA.NUM_DOCUMENTO%TYPE
    ) RETURN BOOLEAN;

END PKG_GESTION_MEDICOS;
/

CREATE OR REPLACE PACKAGE BODY PKG_GESTION_MEDICOS AS

    E_MEDICO_NO_EXISTE     EXCEPTION;
    E_EMAIL_INVALIDO       EXCEPTION;
    E_INTERVALO_INVALIDO   EXCEPTION;

    PROCEDURE INSERTAR_MEDICO(
        P_TIPO_DOCUMENTO    IN MEDICO_TERAPISTA.TIPO_DOCUMENTO%TYPE,
        P_NUM_DOCUMENTO     IN MEDICO_TERAPISTA.NUM_DOCUMENTO%TYPE,
        P_NOMBRES           IN MEDICO_TERAPISTA.NOMBRES%TYPE,
        P_APELLIDOS         IN MEDICO_TERAPISTA.APELLIDOS%TYPE,
        P_TIPO_PROFESIONAL  IN MEDICO_TERAPISTA.TIPO_PROFESIONAL%TYPE,
        P_INTERVALO_MINUTOS IN MEDICO_TERAPISTA.INTERVALO_MINUTOS%TYPE,
        P_TELEFONO          IN MEDICO_TERAPISTA.TELEFONO%TYPE,
        P_EMAIL             IN MEDICO_TERAPISTA.EMAIL%TYPE,
        P_ID_GENERADO       OUT MEDICO_TERAPISTA.ID_MEDICO%TYPE
    ) IS
    BEGIN
        IF P_INTERVALO_MINUTOS NOT IN (15, 30, 45, 60) THEN
            RAISE E_INTERVALO_INVALIDO;
        END IF;

        IF P_EMAIL IS NOT NULL AND NOT REGEXP_LIKE(P_EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
            RAISE E_EMAIL_INVALIDO;
        END IF;

        P_ID_GENERADO := SEQ_MEDICO.NEXTVAL;

        INSERT INTO MEDICO_TERAPISTA(
            ID_MEDICO,
            TIPO_DOCUMENTO,
            NUM_DOCUMENTO,
            NOMBRES,
            APELLIDOS,
            TIPO_PROFESIONAL,
            INTERVALO_MINUTOS,
            TELEFONO,
            EMAIL,
            ESTADO
        ) VALUES (
            P_ID_GENERADO,
            UPPER(P_TIPO_DOCUMENTO),
            P_NUM_DOCUMENTO,
            INITCAP(P_NOMBRES),
            INITCAP(P_APELLIDOS),
            INITCAP(P_TIPO_PROFESIONAL),
            P_INTERVALO_MINUTOS,
            P_TELEFONO,
            LOWER(P_EMAIL),
            'A'
        );

        DBMS_OUTPUT.PUT_LINE('Medico/Terapista insertado con ID: ' || P_ID_GENERADO);

    EXCEPTION
        WHEN E_INTERVALO_INVALIDO THEN
            RAISE_APPLICATION_ERROR(-20301, 'El intervalo del profesional debe ser 15, 30, 45 o 60 minutos.');
        WHEN E_EMAIL_INVALIDO THEN
            RAISE_APPLICATION_ERROR(-20302, 'El correo del medico/terapista no tiene formato valido.');
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20303, 'Ya existe un medico/terapista con ese numero de documento.');
        WHEN VALUE_ERROR THEN
            RAISE_APPLICATION_ERROR(-20304, 'Error de tipo o longitud en los datos del medico/terapista.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20305, 'Error inesperado al insertar medico/terapista: ' || SQLERRM);
    END INSERTAR_MEDICO;

    PROCEDURE ACTUALIZAR_MEDICO(
        P_ID_MEDICO         IN MEDICO_TERAPISTA.ID_MEDICO%TYPE,
        P_TELEFONO          IN MEDICO_TERAPISTA.TELEFONO%TYPE,
        P_EMAIL             IN MEDICO_TERAPISTA.EMAIL%TYPE,
        P_INTERVALO_MINUTOS IN MEDICO_TERAPISTA.INTERVALO_MINUTOS%TYPE
    ) IS
        V_TOTAL NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_TOTAL
        FROM MEDICO_TERAPISTA
        WHERE ID_MEDICO = P_ID_MEDICO;

        IF V_TOTAL = 0 THEN
            RAISE E_MEDICO_NO_EXISTE;
        END IF;

        IF P_INTERVALO_MINUTOS NOT IN (15, 30, 45, 60) THEN
            RAISE E_INTERVALO_INVALIDO;
        END IF;

        IF P_EMAIL IS NOT NULL AND NOT REGEXP_LIKE(P_EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
            RAISE E_EMAIL_INVALIDO;
        END IF;

        UPDATE MEDICO_TERAPISTA
        SET TELEFONO = P_TELEFONO,
            EMAIL = LOWER(P_EMAIL),
            INTERVALO_MINUTOS = P_INTERVALO_MINUTOS
        WHERE ID_MEDICO = P_ID_MEDICO;

        DBMS_OUTPUT.PUT_LINE('Medico/Terapista actualizado: ' || P_ID_MEDICO);

    EXCEPTION
        WHEN E_MEDICO_NO_EXISTE THEN
            RAISE_APPLICATION_ERROR(-20306, 'No existe el medico/terapista que se desea actualizar.');
        WHEN E_INTERVALO_INVALIDO THEN
            RAISE_APPLICATION_ERROR(-20307, 'El intervalo actualizado debe ser 15, 30, 45 o 60 minutos.');
        WHEN E_EMAIL_INVALIDO THEN
            RAISE_APPLICATION_ERROR(-20308, 'El correo actualizado no tiene formato valido.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20309, 'Error inesperado al actualizar medico/terapista: ' || SQLERRM);
    END ACTUALIZAR_MEDICO;

    PROCEDURE CONSULTAR_MEDICO(
        P_ID_MEDICO IN MEDICO_TERAPISTA.ID_MEDICO%TYPE,
        P_MEDICO    OUT T_MEDICO_REC
    ) IS
    BEGIN
        SELECT ID_MEDICO, TIPO_DOCUMENTO, NUM_DOCUMENTO, NOMBRES, APELLIDOS,
               TIPO_PROFESIONAL, INTERVALO_MINUTOS, TELEFONO, EMAIL, ESTADO
        INTO P_MEDICO
        FROM MEDICO_TERAPISTA
        WHERE ID_MEDICO = P_ID_MEDICO;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20310, 'No existe el medico/terapista consultado.');
        WHEN TOO_MANY_ROWS THEN
            RAISE_APPLICATION_ERROR(-20311, 'La consulta retorno mas de un medico/terapista.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20312, 'Error inesperado al consultar medico/terapista: ' || SQLERRM);
    END CONSULTAR_MEDICO;

    PROCEDURE ELIMINAR_MEDICO(
        P_ID_MEDICO IN MEDICO_TERAPISTA.ID_MEDICO%TYPE
    ) IS
        V_TOTAL NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_TOTAL
        FROM MEDICO_TERAPISTA
        WHERE ID_MEDICO = P_ID_MEDICO;

        IF V_TOTAL = 0 THEN
            RAISE E_MEDICO_NO_EXISTE;
        END IF;

        UPDATE MEDICO_TERAPISTA
        SET ESTADO = 'I'
        WHERE ID_MEDICO = P_ID_MEDICO;

        DBMS_OUTPUT.PUT_LINE('Medico/Terapista inactivado: ' || P_ID_MEDICO);

    EXCEPTION
        WHEN E_MEDICO_NO_EXISTE THEN
            RAISE_APPLICATION_ERROR(-20313, 'No existe el medico/terapista que se desea eliminar/inactivar.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20314, 'Error inesperado al eliminar medico/terapista: ' || SQLERRM);
    END ELIMINAR_MEDICO;

    FUNCTION EXISTE_MEDICO(
        P_NUM_DOCUMENTO IN MEDICO_TERAPISTA.NUM_DOCUMENTO%TYPE
    ) RETURN BOOLEAN IS
        V_TOTAL NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_TOTAL
        FROM MEDICO_TERAPISTA
        WHERE NUM_DOCUMENTO = P_NUM_DOCUMENTO;

        RETURN V_TOTAL > 0;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN FALSE;
    END EXISTE_MEDICO;

END PKG_GESTION_MEDICOS;
/

/* ============================================================================
   b) CUARTO PAQUETE CRUD - MEDICAMENTOS
   d) MANEJO DE EXCEPCIONES
============================================================================ */
CREATE OR REPLACE PACKAGE PKG_GESTION_MEDICAMENTOS AS

    TYPE T_MEDICAMENTO_REC IS RECORD (
        ID_MEDICAMENTO MEDICAMENTO.ID_MEDICAMENTO%TYPE,
        NOMBRE         MEDICAMENTO.NOMBRE%TYPE,
        PRESENTACION   MEDICAMENTO.PRESENTACION%TYPE,
        ESTADO         MEDICAMENTO.ESTADO%TYPE
    );

    PROCEDURE INSERTAR_MEDICAMENTO(
        P_NOMBRE        IN MEDICAMENTO.NOMBRE%TYPE,
        P_PRESENTACION  IN MEDICAMENTO.PRESENTACION%TYPE,
        P_ID_GENERADO   OUT MEDICAMENTO.ID_MEDICAMENTO%TYPE
    );

    PROCEDURE ACTUALIZAR_MEDICAMENTO(
        P_ID_MEDICAMENTO IN MEDICAMENTO.ID_MEDICAMENTO%TYPE,
        P_NOMBRE         IN MEDICAMENTO.NOMBRE%TYPE,
        P_PRESENTACION   IN MEDICAMENTO.PRESENTACION%TYPE
    );

    PROCEDURE CONSULTAR_MEDICAMENTO(
        P_ID_MEDICAMENTO IN MEDICAMENTO.ID_MEDICAMENTO%TYPE,
        P_MEDICAMENTO    OUT T_MEDICAMENTO_REC
    );

    PROCEDURE ELIMINAR_MEDICAMENTO(
        P_ID_MEDICAMENTO IN MEDICAMENTO.ID_MEDICAMENTO%TYPE
    );

    FUNCTION EXISTE_MEDICAMENTO(
        P_NOMBRE IN MEDICAMENTO.NOMBRE%TYPE
    ) RETURN BOOLEAN;

END PKG_GESTION_MEDICAMENTOS;
/

CREATE OR REPLACE PACKAGE BODY PKG_GESTION_MEDICAMENTOS AS

    E_MEDICAMENTO_NO_EXISTE EXCEPTION;
    E_NOMBRE_INVALIDO       EXCEPTION;

    PROCEDURE INSERTAR_MEDICAMENTO(
        P_NOMBRE        IN MEDICAMENTO.NOMBRE%TYPE,
        P_PRESENTACION  IN MEDICAMENTO.PRESENTACION%TYPE,
        P_ID_GENERADO   OUT MEDICAMENTO.ID_MEDICAMENTO%TYPE
    ) IS
    BEGIN
        IF P_NOMBRE IS NULL OR LENGTH(TRIM(P_NOMBRE)) < 3 THEN
            RAISE E_NOMBRE_INVALIDO;
        END IF;

        P_ID_GENERADO := SEQ_MEDICAMENTO.NEXTVAL;

        INSERT INTO MEDICAMENTO(
            ID_MEDICAMENTO,
            NOMBRE,
            PRESENTACION,
            ESTADO
        ) VALUES (
            P_ID_GENERADO,
            INITCAP(TRIM(P_NOMBRE)),
            INITCAP(TRIM(P_PRESENTACION)),
            'A'
        );

        DBMS_OUTPUT.PUT_LINE('Medicamento insertado con ID: ' || P_ID_GENERADO);

    EXCEPTION
        WHEN E_NOMBRE_INVALIDO THEN
            RAISE_APPLICATION_ERROR(-20401, 'El nombre del medicamento debe tener minimo 3 caracteres.');
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20402, 'Ya existe un medicamento con ese nombre.');
        WHEN VALUE_ERROR THEN
            RAISE_APPLICATION_ERROR(-20403, 'Error de tipo o longitud en los datos del medicamento.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20404, 'Error inesperado al insertar medicamento: ' || SQLERRM);
    END INSERTAR_MEDICAMENTO;

    PROCEDURE ACTUALIZAR_MEDICAMENTO(
        P_ID_MEDICAMENTO IN MEDICAMENTO.ID_MEDICAMENTO%TYPE,
        P_NOMBRE         IN MEDICAMENTO.NOMBRE%TYPE,
        P_PRESENTACION   IN MEDICAMENTO.PRESENTACION%TYPE
    ) IS
        V_TOTAL NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_TOTAL
        FROM MEDICAMENTO
        WHERE ID_MEDICAMENTO = P_ID_MEDICAMENTO;

        IF V_TOTAL = 0 THEN
            RAISE E_MEDICAMENTO_NO_EXISTE;
        END IF;

        IF P_NOMBRE IS NULL OR LENGTH(TRIM(P_NOMBRE)) < 3 THEN
            RAISE E_NOMBRE_INVALIDO;
        END IF;

        UPDATE MEDICAMENTO
        SET NOMBRE = INITCAP(TRIM(P_NOMBRE)),
            PRESENTACION = INITCAP(TRIM(P_PRESENTACION))
        WHERE ID_MEDICAMENTO = P_ID_MEDICAMENTO;

        DBMS_OUTPUT.PUT_LINE('Medicamento actualizado: ' || P_ID_MEDICAMENTO);

    EXCEPTION
        WHEN E_MEDICAMENTO_NO_EXISTE THEN
            RAISE_APPLICATION_ERROR(-20405, 'No existe el medicamento que se desea actualizar.');
        WHEN E_NOMBRE_INVALIDO THEN
            RAISE_APPLICATION_ERROR(-20406, 'El nombre actualizado debe tener minimo 3 caracteres.');
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20407, 'Ya existe otro medicamento con ese nombre.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20408, 'Error inesperado al actualizar medicamento: ' || SQLERRM);
    END ACTUALIZAR_MEDICAMENTO;

    PROCEDURE CONSULTAR_MEDICAMENTO(
        P_ID_MEDICAMENTO IN MEDICAMENTO.ID_MEDICAMENTO%TYPE,
        P_MEDICAMENTO    OUT T_MEDICAMENTO_REC
    ) IS
    BEGIN
        SELECT ID_MEDICAMENTO, NOMBRE, PRESENTACION, ESTADO
        INTO P_MEDICAMENTO
        FROM MEDICAMENTO
        WHERE ID_MEDICAMENTO = P_ID_MEDICAMENTO;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20409, 'No existe el medicamento consultado.');
        WHEN TOO_MANY_ROWS THEN
            RAISE_APPLICATION_ERROR(-20410, 'La consulta retorno mas de un medicamento.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20411, 'Error inesperado al consultar medicamento: ' || SQLERRM);
    END CONSULTAR_MEDICAMENTO;

    PROCEDURE ELIMINAR_MEDICAMENTO(
        P_ID_MEDICAMENTO IN MEDICAMENTO.ID_MEDICAMENTO%TYPE
    ) IS
        V_TOTAL NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_TOTAL
        FROM MEDICAMENTO
        WHERE ID_MEDICAMENTO = P_ID_MEDICAMENTO;

        IF V_TOTAL = 0 THEN
            RAISE E_MEDICAMENTO_NO_EXISTE;
        END IF;

        UPDATE MEDICAMENTO
        SET ESTADO = 'I'
        WHERE ID_MEDICAMENTO = P_ID_MEDICAMENTO;

        DBMS_OUTPUT.PUT_LINE('Medicamento inactivado: ' || P_ID_MEDICAMENTO);

    EXCEPTION
        WHEN E_MEDICAMENTO_NO_EXISTE THEN
            RAISE_APPLICATION_ERROR(-20412, 'No existe el medicamento que se desea eliminar/inactivar.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20413, 'Error inesperado al eliminar medicamento: ' || SQLERRM);
    END ELIMINAR_MEDICAMENTO;

    FUNCTION EXISTE_MEDICAMENTO(
        P_NOMBRE IN MEDICAMENTO.NOMBRE%TYPE
    ) RETURN BOOLEAN IS
        V_TOTAL NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_TOTAL
        FROM MEDICAMENTO
        WHERE UPPER(NOMBRE) = UPPER(TRIM(P_NOMBRE));

        RETURN V_TOTAL > 0;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN FALSE;
    END EXISTE_MEDICAMENTO;

END PKG_GESTION_MEDICAMENTOS;
/

/* ============================================================================
   g) TRIGGERS - REGLAS DE NEGOCIO RELACIONADAS CON RESTRICCIONES DE DATOS
   k) Regla de negocio de formato: HORA_CITA HH24:MI y correo valido.
============================================================================ */

/* Trigger 1: valida fecha y formato de hora de la cita. */
CREATE OR REPLACE TRIGGER TRG_CITA_VALIDAR_FECHA_HORA
BEFORE INSERT OR UPDATE OF FECHA_CITA, HORA_CITA, ESTADO ON CITA
FOR EACH ROW
BEGIN
    IF :NEW.FECHA_CITA < TRUNC(SYSDATE) AND :NEW.ESTADO IN ('PROGRAMADA','REPROGRAMADA') THEN
        RAISE_APPLICATION_ERROR(-20101, 'No se puede programar o reprogramar una cita en una fecha pasada.');
    END IF;

    IF NOT REGEXP_LIKE(:NEW.HORA_CITA, '^([01][0-9]|2[0-3]):[0-5][0-9]$') THEN
        RAISE_APPLICATION_ERROR(-20102, 'La hora de la cita debe tener formato HH24:MI, ejemplo 08:30.');
    END IF;
END;
/

/* Trigger 2: valida formato de datos del paciente y normaliza nombres/correo. */
CREATE OR REPLACE TRIGGER TRG_PACIENTE_VALIDAR_FORMATOS
BEFORE INSERT OR UPDATE ON PACIENTE
FOR EACH ROW
BEGIN
    :NEW.TIPO_DOCUMENTO := UPPER(:NEW.TIPO_DOCUMENTO);
    :NEW.NOMBRES := INITCAP(:NEW.NOMBRES);
    :NEW.APELLIDOS := INITCAP(:NEW.APELLIDOS);

    IF :NEW.FECHA_NACIMIENTO > TRUNC(SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20103, 'La fecha de nacimiento no puede ser futura.');
    END IF;

    IF :NEW.EMAIL IS NOT NULL THEN
        :NEW.EMAIL := LOWER(:NEW.EMAIL);
        IF NOT REGEXP_LIKE(:NEW.EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
            RAISE_APPLICATION_ERROR(-20104, 'El email del paciente no tiene un formato valido.');
        END IF;
    END IF;

    IF :NEW.CELULAR IS NOT NULL AND NOT REGEXP_LIKE(:NEW.CELULAR, '^[0-9]{10}$') THEN
        RAISE_APPLICATION_ERROR(-20105, 'El celular debe contener exactamente 10 digitos numericos.');
    END IF;
END;
/

/* Trigger 3: valida intervalos permitidos del medico/terapista. */
CREATE OR REPLACE TRIGGER TRG_MEDICO_VALIDAR_INTERVALO
BEFORE INSERT OR UPDATE OF INTERVALO_MINUTOS, EMAIL ON MEDICO_TERAPISTA
FOR EACH ROW
BEGIN
    CASE :NEW.INTERVALO_MINUTOS
        WHEN 15 THEN NULL;
        WHEN 30 THEN NULL;
        WHEN 45 THEN NULL;
        WHEN 60 THEN NULL;
        ELSE RAISE_APPLICATION_ERROR(-20106, 'El intervalo del profesional solo puede ser 15, 30, 45 o 60 minutos.');
    END CASE;

    IF :NEW.EMAIL IS NOT NULL THEN
        :NEW.EMAIL := LOWER(:NEW.EMAIL);
        IF NOT REGEXP_LIKE(:NEW.EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
            RAISE_APPLICATION_ERROR(-20107, 'El email del medico/terapista no tiene formato valido.');
        END IF;
    END IF;
END;
/

/* Trigger 4: solo permite historia clinica si la cita esta atendida. */
CREATE OR REPLACE TRIGGER TRG_HISTORIA_SOLO_CITA_ATENDIDA
BEFORE INSERT OR UPDATE OF ID_CITA ON HISTORIA_CLINICA
FOR EACH ROW
DECLARE
    V_ESTADO CITA.ESTADO%TYPE;
BEGIN
    SELECT ESTADO INTO V_ESTADO
    FROM CITA
    WHERE ID_CITA = :NEW.ID_CITA;

    IF V_ESTADO <> 'ATENDIDA' THEN
        RAISE_APPLICATION_ERROR(-20108, 'Solo se puede crear historia clinica para citas en estado ATENDIDA.');
    END IF;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20109, 'La cita asociada a la historia clinica no existe.');
END;
/

/* Trigger 5 adicional: auditoria automatica de cambios sobre CITA. */
CREATE OR REPLACE TRIGGER TRG_CITA_AUDITORIA
AFTER INSERT OR UPDATE OR DELETE ON CITA
FOR EACH ROW
DECLARE
    V_ACCION AUDITORIA.ACCION%TYPE;
    V_DESC   AUDITORIA.DESCRIPCION%TYPE;
BEGIN
    IF INSERTING THEN
        V_ACCION := 'INSERTAR_CITA';
        V_DESC := 'Se inserto la cita ' || :NEW.ID_CITA || ' para el paciente ' || :NEW.ID_PACIENTE;
    ELSIF UPDATING THEN
        V_ACCION := 'ACTUALIZAR_CITA';
        V_DESC := 'La cita ' || :NEW.ID_CITA || ' cambio de estado ' || :OLD.ESTADO || ' a ' || :NEW.ESTADO;
    ELSE
        V_ACCION := 'ELIMINAR_CITA';
        V_DESC := 'Se elimino la cita ' || :OLD.ID_CITA;
    END IF;

    INSERT INTO AUDITORIA(ID_AUDITORIA, ID_USUARIO, FECHA_EVENTO, ACCION, TABLA_AFECTADA, DESCRIPCION)
    VALUES(SEQ_AUDITORIA.NEXTVAL, 1, SYSDATE, V_ACCION, 'CITA', V_DESC);
END;
/

/* ============================================================================
   a) BLOQUES ANONIMOS COMO REPORTES - MINIMO 5
   c) Estructuras de control/repetitivas: IF, CASE, WHILE, FOR, LOOP.
   e) Cursores: minimo 4, uno con parametros.
   f) Tipos compuestos: RECORD, TABLE y BULK COLLECT.
============================================================================ */

/* ----------------------------------------------------------------------------
   REPORTE 1: Citas por profesional usando cursor explicito, FOR y CASE.
   Cursor 1.
---------------------------------------------------------------------------- */
DECLARE
    CURSOR C_CITAS_PROFESIONAL IS
        SELECT M.ID_MEDICO,
               M.NOMBRES || ' ' || M.APELLIDOS AS PROFESIONAL,
               COUNT(C.ID_CITA) AS TOTAL_CITAS
        FROM MEDICO_TERAPISTA M
        LEFT JOIN CITA C ON C.ID_MEDICO = M.ID_MEDICO
        GROUP BY M.ID_MEDICO, M.NOMBRES, M.APELLIDOS
        ORDER BY TOTAL_CITAS DESC;

    V_CLASIFICACION VARCHAR2(30);
BEGIN
    DBMS_OUTPUT.PUT_LINE('REPORTE 1: CANTIDAD DE CITAS POR PROFESIONAL');

    FOR R IN C_CITAS_PROFESIONAL LOOP
        CASE
            WHEN R.TOTAL_CITAS = 0 THEN V_CLASIFICACION := 'SIN CITAS';
            WHEN R.TOTAL_CITAS BETWEEN 1 AND 2 THEN V_CLASIFICACION := 'CARGA BAJA';
            ELSE V_CLASIFICACION := 'CARGA ALTA';
        END CASE;

        DBMS_OUTPUT.PUT_LINE(R.PROFESIONAL || ' -> ' || R.TOTAL_CITAS || ' citas - ' || V_CLASIFICACION);
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error en reporte 1: ' || SQLERRM);
END;
/

/* ----------------------------------------------------------------------------
   REPORTE 2: Citas de un paciente usando cursor con parametro e IF.
   Cursor 2 parametrizado.
---------------------------------------------------------------------------- */
DECLARE
    CURSOR C_CITAS_PACIENTE(P_ID_PACIENTE NUMBER) IS
        SELECT C.ID_CITA, C.FECHA_CITA, C.HORA_CITA, C.ESTADO,
               M.NOMBRES || ' ' || M.APELLIDOS AS PROFESIONAL
        FROM CITA C
        INNER JOIN MEDICO_TERAPISTA M ON M.ID_MEDICO = C.ID_MEDICO
        WHERE C.ID_PACIENTE = P_ID_PACIENTE
        ORDER BY C.FECHA_CITA, C.HORA_CITA;

    V_ID_PACIENTE PACIENTE.ID_PACIENTE%TYPE := 1;
    V_TOTAL NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('REPORTE 2: CITAS DEL PACIENTE ID ' || V_ID_PACIENTE);

    FOR R IN C_CITAS_PACIENTE(V_ID_PACIENTE) LOOP
        V_TOTAL := V_TOTAL + 1;
        DBMS_OUTPUT.PUT_LINE('Cita ' || R.ID_CITA || ' - ' || TO_CHAR(R.FECHA_CITA,'YYYY-MM-DD') ||
                             ' ' || R.HORA_CITA || ' - ' || R.ESTADO || ' - ' || R.PROFESIONAL);
    END LOOP;

    IF V_TOTAL = 0 THEN
        DBMS_OUTPUT.PUT_LINE('El paciente no tiene citas registradas.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Total citas encontradas: ' || V_TOTAL);
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error en reporte 2: ' || SQLERRM);
END;
/

/* ----------------------------------------------------------------------------
   REPORTE 3: Auditoria usando cursor explicito, WHILE y FETCH.
   Cursor 3.
---------------------------------------------------------------------------- */
DECLARE
    CURSOR C_AUDITORIA IS
        SELECT A.ID_AUDITORIA, A.FECHA_EVENTO, A.ACCION, A.TABLA_AFECTADA, U.NOMBRE_USUARIO
        FROM AUDITORIA A
        INNER JOIN USUARIO_SISTEMA U ON U.ID_USUARIO = A.ID_USUARIO
        ORDER BY A.FECHA_EVENTO DESC;

    V_REG C_AUDITORIA%ROWTYPE;
    V_CONTADOR NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('REPORTE 3: EVENTOS DE AUDITORIA');

    OPEN C_AUDITORIA;
    FETCH C_AUDITORIA INTO V_REG;

    WHILE C_AUDITORIA%FOUND LOOP
        V_CONTADOR := V_CONTADOR + 1;
        DBMS_OUTPUT.PUT_LINE(V_CONTADOR || '. ' || TO_CHAR(V_REG.FECHA_EVENTO,'YYYY-MM-DD HH24:MI') ||
                             ' - ' || V_REG.ACCION || ' - ' || V_REG.TABLA_AFECTADA ||
                             ' - Usuario: ' || V_REG.NOMBRE_USUARIO);
        FETCH C_AUDITORIA INTO V_REG;
    END LOOP;

    CLOSE C_AUDITORIA;
EXCEPTION
    WHEN OTHERS THEN
        IF C_AUDITORIA%ISOPEN THEN
            CLOSE C_AUDITORIA;
        END IF;
        DBMS_OUTPUT.PUT_LINE('Error en reporte 3: ' || SQLERRM);
END;
/

/* ----------------------------------------------------------------------------
   REPORTE 4: Medicamentos por historia clinica usando RECORD y LOOP.
   Cursor 4.
---------------------------------------------------------------------------- */
DECLARE
    TYPE T_MEDICAMENTO_REC IS RECORD (
        ID_HISTORIA    HISTORIA_MEDICAMENTO.ID_HISTORIA%TYPE,
        ID_MEDICAMENTO MEDICAMENTO.ID_MEDICAMENTO%TYPE,
        NOMBRE         MEDICAMENTO.NOMBRE%TYPE,
        DOSIS          HISTORIA_MEDICAMENTO.DOSIS%TYPE,
        FRECUENCIA     HISTORIA_MEDICAMENTO.FRECUENCIA%TYPE
    );

    CURSOR C_MEDICAMENTOS IS
        SELECT HM.ID_HISTORIA, M.ID_MEDICAMENTO, M.NOMBRE,
               HM.DOSIS, HM.FRECUENCIA
        FROM HISTORIA_MEDICAMENTO HM
        INNER JOIN MEDICAMENTO M ON M.ID_MEDICAMENTO = HM.ID_MEDICAMENTO
        ORDER BY HM.ID_HISTORIA, M.NOMBRE;

    V_MED              T_MEDICAMENTO_REC;
    V_HISTORIA_ANTERIOR NUMBER := -1;
    V_TOTAL            NUMBER := 0;   -- ← variable para guardar conteo antes de cerrar
BEGIN
    DBMS_OUTPUT.PUT_LINE('REPORTE 4: MEDICAMENTOS POR HISTORIA CLINICA');

    OPEN C_MEDICAMENTOS;
    LOOP
        FETCH C_MEDICAMENTOS INTO V_MED;
        EXIT WHEN C_MEDICAMENTOS%NOTFOUND;

        V_TOTAL := V_TOTAL + 1;

        IF V_MED.ID_HISTORIA <> V_HISTORIA_ANTERIOR THEN
            DBMS_OUTPUT.PUT_LINE('-- Historia ID: ' || V_MED.ID_HISTORIA);
            V_HISTORIA_ANTERIOR := V_MED.ID_HISTORIA;
        END IF;

        DBMS_OUTPUT.PUT_LINE('   Medicamento: ' || V_MED.NOMBRE ||
                             ' | Dosis: '       || V_MED.DOSIS  ||
                             ' | Frecuencia: '  || V_MED.FRECUENCIA);
    END LOOP;

    V_TOTAL := C_MEDICAMENTOS%ROWCOUNT;   -- ← guardar ANTES de cerrar
    CLOSE C_MEDICAMENTOS;                 -- ← cerrar despues

    IF V_TOTAL = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No hay medicamentos registrados.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        IF C_MEDICAMENTOS%ISOPEN THEN CLOSE C_MEDICAMENTOS; END IF;
        DBMS_OUTPUT.PUT_LINE('Error en reporte 4: ' || SQLERRM);
END;
/

/* ----------------------------------------------------------------------------
   REPORTE 5: Pacientes activos usando TABLE y BULK COLLECT.
   Cumple tipo compuesto TABLE y BULK COLLECT.
---------------------------------------------------------------------------- */
DECLARE
    TYPE T_PACIENTE_TAB IS TABLE OF PACIENTE%ROWTYPE;
    V_PACIENTES T_PACIENTE_TAB;
BEGIN
    DBMS_OUTPUT.PUT_LINE('REPORTE 5: PACIENTES ACTIVOS CARGADOS CON BULK COLLECT');

    SELECT *
    BULK COLLECT INTO V_PACIENTES
    FROM PACIENTE
    WHERE ESTADO = 'A'
    ORDER BY APELLIDOS, NOMBRES;

    IF V_PACIENTES.COUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No hay pacientes activos.');
    ELSE
        FOR I IN 1 .. V_PACIENTES.COUNT LOOP
            DBMS_OUTPUT.PUT_LINE(I || '. ' || V_PACIENTES(I).NOMBRES || ' ' ||
                                 V_PACIENTES(I).APELLIDOS || ' - Doc: ' ||
                                 V_PACIENTES(I).NUM_DOCUMENTO || ' - Email: ' ||
                                 NVL(V_PACIENTES(I).EMAIL, 'SIN EMAIL'));
        END LOOP;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error en reporte 5: ' || SQLERRM);
END;
/

/* ============================================================================
   BLOQUE DE PRUEBA DEL PAQUETE CRUD
============================================================================ */
DECLARE
    V_ID PACIENTE.ID_PACIENTE%TYPE;
    V_PACIENTE PKG_GESTION_PACIENTES.T_PACIENTE_REC;
BEGIN
    IF PKG_GESTION_PACIENTES.EXISTE_PACIENTE('1999999999') THEN
        SELECT ID_PACIENTE INTO V_ID
        FROM PACIENTE
        WHERE NUM_DOCUMENTO = '1999999999';

        UPDATE PACIENTE
        SET ESTADO = 'A'
        WHERE ID_PACIENTE = V_ID;

        DBMS_OUTPUT.PUT_LINE('Paciente de prueba ya existia. Se reutiliza ID: ' || V_ID);
    ELSE
        PKG_GESTION_PACIENTES.INSERTAR_PACIENTE(
            P_TIPO_DOCUMENTO   => 'CC',
            P_NUM_DOCUMENTO    => '1999999999',
            P_NOMBRES          => 'Paciente',
            P_APELLIDOS        => 'Prueba',
            P_FECHA_NACIMIENTO => TO_DATE('2000-01-15','YYYY-MM-DD'),
            P_CELULAR          => '3001234567',
            P_DIRECCION        => 'Popayan',
            P_EMAIL            => 'paciente.prueba@correo.com',
            P_ID_GENERADO      => V_ID
        );
    END IF;

    PKG_GESTION_PACIENTES.ACTUALIZAR_PACIENTE(
        P_ID_PACIENTE => V_ID,
        P_CELULAR     => '3007654321',
        P_DIRECCION   => 'Popayan - Cauca',
        P_EMAIL       => 'paciente.actualizado@correo.com'
    );

    PKG_GESTION_PACIENTES.CONSULTAR_PACIENTE(V_ID, V_PACIENTE);
    DBMS_OUTPUT.PUT_LINE('Consulta CRUD: ' || V_PACIENTE.NOMBRES || ' ' || V_PACIENTE.APELLIDOS ||
                         ' - ' || V_PACIENTE.EMAIL);

    PKG_GESTION_PACIENTES.ELIMINAR_PACIENTE(V_ID);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error probando paquete CRUD: ' || SQLERRM);
END;
/

/* ============================================================================
   BLOQUE DE PRUEBA DEL PAQUETE CRUD DE CITAS
============================================================================ */
DECLARE
    V_ID_CITA CITA.ID_CITA%TYPE;
    V_CITA    PKG_GESTION_CITAS.T_CITA_REC;
BEGIN
    PKG_GESTION_CITAS.INSERTAR_CITA(
        P_ID_PACIENTE   => 1,
        P_ID_MEDICO     => 1,
        P_FECHA_CITA    => TRUNC(SYSDATE) + 2,
        P_HORA_CITA     => '16:30',
        P_MOTIVO        => 'Consulta general de prueba',
        P_OBSERVACIONES => 'Registro creado desde prueba del paquete CRUD.',
        P_ID_GENERADO   => V_ID_CITA
    );

    PKG_GESTION_CITAS.ACTUALIZAR_CITA(
        P_ID_CITA       => V_ID_CITA,
        P_ID_MEDICO     => 1,
        P_FECHA_CITA    => TRUNC(SYSDATE) + 3,
        P_HORA_CITA     => '17:00',
        P_ESTADO        => 'REPROGRAMADA',
        P_MOTIVO        => 'Consulta general reprogramada',
        P_OBSERVACIONES => 'Cita actualizada desde prueba del paquete CRUD.'
    );

    PKG_GESTION_CITAS.ACTUALIZAR_ESTADO_CITA(
        P_ID_CITA => V_ID_CITA,
        P_ESTADO  => 'ATENDIDA'
    );

    PKG_GESTION_CITAS.CONSULTAR_CITA(
        P_ID_CITA => V_ID_CITA,
        P_CITA    => V_CITA
    );

    DBMS_OUTPUT.PUT_LINE(
        'Consulta cita -> ID: ' || V_CITA.ID_CITA ||
        ' | Estado: ' || V_CITA.ESTADO ||
        ' | Fecha: ' || TO_CHAR(V_CITA.FECHA_CITA,'YYYY-MM-DD') ||
        ' | Hora: ' || V_CITA.HORA_CITA ||
        ' | Motivo: ' || V_CITA.MOTIVO
    );

    PKG_GESTION_CITAS.ELIMINAR_CITA(V_ID_CITA);

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error probando paquete CRUD de citas: ' || SQLERRM);
END;
/

/* ============================================================================
   BLOQUE DE PRUEBA DEL PAQUETE CRUD DE MEDICOS/TERAPISTAS
============================================================================ */
DECLARE
    V_ID_MEDICO MEDICO_TERAPISTA.ID_MEDICO%TYPE;
    V_MEDICO    PKG_GESTION_MEDICOS.T_MEDICO_REC;
BEGIN
    IF PKG_GESTION_MEDICOS.EXISTE_MEDICO('8888888888') THEN
        SELECT ID_MEDICO INTO V_ID_MEDICO
        FROM MEDICO_TERAPISTA
        WHERE NUM_DOCUMENTO = '8888888888';

        UPDATE MEDICO_TERAPISTA
        SET ESTADO = 'A'
        WHERE ID_MEDICO = V_ID_MEDICO;

        DBMS_OUTPUT.PUT_LINE('Medico/Terapista de prueba ya existia. Se reutiliza ID: ' || V_ID_MEDICO);
    ELSE
        PKG_GESTION_MEDICOS.INSERTAR_MEDICO(
            P_TIPO_DOCUMENTO    => 'CC',
            P_NUM_DOCUMENTO     => '8888888888',
            P_NOMBRES           => 'Medico',
            P_APELLIDOS         => 'Prueba',
            P_TIPO_PROFESIONAL  => 'Medico General',
            P_INTERVALO_MINUTOS => 30,
            P_TELEFONO          => '3123456789',
            P_EMAIL             => 'medico.prueba@correo.com',
            P_ID_GENERADO       => V_ID_MEDICO
        );
    END IF;

    PKG_GESTION_MEDICOS.ACTUALIZAR_MEDICO(
        P_ID_MEDICO         => V_ID_MEDICO,
        P_TELEFONO          => '3109876543',
        P_EMAIL             => 'medico.actualizado@correo.com',
        P_INTERVALO_MINUTOS => 45
    );

    PKG_GESTION_MEDICOS.CONSULTAR_MEDICO(V_ID_MEDICO, V_MEDICO);

    DBMS_OUTPUT.PUT_LINE(
        'Consulta medico -> ' || V_MEDICO.NOMBRES || ' ' || V_MEDICO.APELLIDOS ||
        ' | Tipo: ' || V_MEDICO.TIPO_PROFESIONAL ||
        ' | Intervalo: ' || V_MEDICO.INTERVALO_MINUTOS
    );

    PKG_GESTION_MEDICOS.ELIMINAR_MEDICO(V_ID_MEDICO);

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error probando paquete CRUD de medicos: ' || SQLERRM);
END;
/

/* ============================================================================
   BLOQUE DE PRUEBA DEL PAQUETE CRUD DE MEDICAMENTOS
============================================================================ */
DECLARE
    V_ID_MEDICAMENTO MEDICAMENTO.ID_MEDICAMENTO%TYPE;
    V_MEDICAMENTO    PKG_GESTION_MEDICAMENTOS.T_MEDICAMENTO_REC;
BEGIN
    IF PKG_GESTION_MEDICAMENTOS.EXISTE_MEDICAMENTO('Medicamento Prueba Pl Sql') THEN
        SELECT ID_MEDICAMENTO INTO V_ID_MEDICAMENTO
        FROM MEDICAMENTO
        WHERE UPPER(NOMBRE) = UPPER('Medicamento Prueba Pl Sql');

        UPDATE MEDICAMENTO
        SET ESTADO = 'A'
        WHERE ID_MEDICAMENTO = V_ID_MEDICAMENTO;

        DBMS_OUTPUT.PUT_LINE('Medicamento de prueba ya existia. Se reutiliza ID: ' || V_ID_MEDICAMENTO);
    ELSE
        PKG_GESTION_MEDICAMENTOS.INSERTAR_MEDICAMENTO(
            P_NOMBRE       => 'Medicamento Prueba Pl Sql',
            P_PRESENTACION => 'Tabletas 500 Mg',
            P_ID_GENERADO  => V_ID_MEDICAMENTO
        );
    END IF;

    PKG_GESTION_MEDICAMENTOS.ACTUALIZAR_MEDICAMENTO(
        P_ID_MEDICAMENTO => V_ID_MEDICAMENTO,
        P_NOMBRE         => 'Medicamento Prueba Pl Sql',
        P_PRESENTACION   => 'Capsulas 250 Mg'
    );

    PKG_GESTION_MEDICAMENTOS.CONSULTAR_MEDICAMENTO(
        P_ID_MEDICAMENTO => V_ID_MEDICAMENTO,
        P_MEDICAMENTO    => V_MEDICAMENTO
    );

    DBMS_OUTPUT.PUT_LINE(
        'Consulta medicamento -> ' || V_MEDICAMENTO.NOMBRE ||
        ' | Presentacion: ' || V_MEDICAMENTO.PRESENTACION ||
        ' | Estado: ' || V_MEDICAMENTO.ESTADO
    );

    PKG_GESTION_MEDICAMENTOS.ELIMINAR_MEDICAMENTO(V_ID_MEDICAMENTO);

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error probando paquete CRUD de medicamentos: ' || SQLERRM);
END;
/

/* ============================================================================
   i) REVISION DE DICCIONARIO DE DATOS - MINIMO 2 CONSULTAS
============================================================================ */

/* Consulta 1: diccionario de tablas del usuario. */
SELECT TABLE_NAME, STATUS, NUM_ROWS
FROM USER_TABLES
WHERE TABLE_NAME IN (
    'ROL','USUARIO_SISTEMA','PACIENTE','ESPECIALIDAD','MEDICO_TERAPISTA',
    'MEDICO_ESPECIALIDAD','CITA','HISTORIA_CLINICA','MEDICAMENTO',
    'HISTORIA_MEDICAMENTO','AUDITORIA','REAGENDAMIENTO'
)
ORDER BY TABLE_NAME;

/* Consulta 2: diccionario de paquetes, procedimientos y funciones creadas. */
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS, CREATED, LAST_DDL_TIME
FROM USER_OBJECTS
WHERE OBJECT_TYPE IN ('PACKAGE','PACKAGE BODY','PROCEDURE','FUNCTION')
ORDER BY OBJECT_TYPE, OBJECT_NAME;

/* Consultas adicionales para evidenciar triggers, indices, secuencias y vistas. */
SELECT TRIGGER_NAME, TABLE_NAME, STATUS
FROM USER_TRIGGERS
WHERE TRIGGER_NAME LIKE 'TRG_%'
ORDER BY TRIGGER_NAME;

SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS
FROM USER_INDEXES
WHERE INDEX_NAME IN ('IDX_CITA_FECHA_ESTADO', 'IDX_PACIENTE_APELLIDOS_NOMBRES', 'UK_CITA_MEDICO_FECHA_HORA')
ORDER BY TABLE_NAME, INDEX_NAME;

SELECT SEQUENCE_NAME, MIN_VALUE, INCREMENT_BY, LAST_NUMBER
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME IN (
    'SEQ_PACIENTE',
    'SEQ_CITA',
    'SEQ_AUDITORIA',
    'SEQ_HISTORIA',
    'SEQ_MEDICO',
    'SEQ_MEDICAMENTO'
)
ORDER BY SEQUENCE_NAME;

SELECT *
FROM VW_RESUMEN_CITAS_PROFESIONAL
ORDER BY PROFESIONAL;

/* ============================================================================
   RESUMEN DE CUMPLIMIENTO
   a) 5 bloques anonimos de reportes: REPORTE 1 al 5.
   b) Paquete CRUD: insertar, actualizar, consultar, eliminar/inactivar.
   c) IF, CASE, WHILE, FOR, LOOP usados en reportes/triggers/paquete.
   d) Mas de 5 manejos de excepciones en paquete y bloques anonimos.
   e) 4 cursores: C_CITAS_PROFESIONAL, C_CITAS_PACIENTE parametrizado,
      C_AUDITORIA, C_MEDICAMENTOS.
   f) RECORD: T_PACIENTE_REC y T_MEDICAMENTO_REC. TABLE: T_PACIENTE_TAB.
      BULK COLLECT: REPORTE 5.
   g) 5 triggers: TRG_CITA_VALIDAR_FECHA_HORA, TRG_PACIENTE_VALIDAR_FORMATOS,
      TRG_MEDICO_VALIDAR_INTERVALO, TRG_HISTORIA_SOLO_CITA_ATENDIDA,
      TRG_CITA_AUDITORIA.
   h) Vista: VW_RESUMEN_CITAS_PROFESIONAL.
   i) Diccionario: USER_TABLES y USER_OBJECTS, mas extras.
   j) Indices y secuencias: 2 indices propios y 4 secuencias.
   k) Formato de datos: hora de cita HH24:MI, correo y celular validados.
============================================================================ */