/* =========================
   TABLA: ROL
   ========================= */
CREATE TABLE ROL (
    ID_ROL              NUMBER(10)      PRIMARY KEY,
    NOMBRE              VARCHAR2(50)    NOT NULL UNIQUE,
    DESCRIPCION         VARCHAR2(200),
    ESTADO              CHAR(1)         DEFAULT 'A' NOT NULL,
    CONSTRAINT CHK_ROL_ESTADO CHECK (ESTADO IN ('A','I'))
);

/* =========================
   TABLA: USUARIO_SISTEMA
   ========================= */
CREATE TABLE USUARIO_SISTEMA (
    ID_USUARIO          NUMBER(10)      PRIMARY KEY,
    NOMBRE_USUARIO      VARCHAR2(50)    NOT NULL UNIQUE,
    CLAVE               VARCHAR2(100)   NOT NULL,
    NOMBRE_COMPLETO     VARCHAR2(100)   NOT NULL,
    EMAIL               VARCHAR2(100),
    ESTADO              CHAR(1)         DEFAULT 'A' NOT NULL,
    ID_ROL              NUMBER(10)      NOT NULL,
    CONSTRAINT CHK_USUARIO_ESTADO CHECK (ESTADO IN ('A','I')),
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ID_ROL)
        REFERENCES ROL(ID_ROL)
);

/* =========================
   TABLA: PACIENTE
   ========================= */
CREATE TABLE PACIENTE (
    ID_PACIENTE         NUMBER(10)      PRIMARY KEY,
    TIPO_DOCUMENTO      VARCHAR2(20)    NOT NULL,
    NUM_DOCUMENTO       VARCHAR2(20)    NOT NULL UNIQUE,
    NOMBRES             VARCHAR2(60)    NOT NULL,
    APELLIDOS           VARCHAR2(60)    NOT NULL,
    FECHA_NACIMIENTO    DATE            NOT NULL,
    CELULAR             VARCHAR2(20),
    DIRECCION           VARCHAR2(120),
    EMAIL               VARCHAR2(100),
    ESTADO              CHAR(1)         DEFAULT 'A' NOT NULL,
    CONSTRAINT CHK_PACIENTE_ESTADO CHECK (ESTADO IN ('A','I'))
);

/* =========================
   TABLA: ESPECIALIDAD
   ========================= */
CREATE TABLE ESPECIALIDAD (
    ID_ESPECIALIDAD     NUMBER(10)      PRIMARY KEY,
    NOMBRE              VARCHAR2(60)    NOT NULL UNIQUE,
    DESCRIPCION         VARCHAR2(200),
    ESTADO              CHAR(1)         DEFAULT 'A' NOT NULL,
    CONSTRAINT CHK_ESPECIALIDAD_ESTADO CHECK (ESTADO IN ('A','I'))
);

/* =========================
   TABLA: MEDICO_TERAPISTA
   ========================= */
CREATE TABLE MEDICO_TERAPISTA (
    ID_MEDICO           NUMBER(10)      PRIMARY KEY,
    TIPO_DOCUMENTO      VARCHAR2(20)    NOT NULL,
    NUM_DOCUMENTO       VARCHAR2(20)    NOT NULL UNIQUE,
    NOMBRES             VARCHAR2(60)    NOT NULL,
    APELLIDOS           VARCHAR2(60)    NOT NULL,
    TIPO_PROFESIONAL    VARCHAR2(30)    NOT NULL,
    INTERVALO_MINUTOS   NUMBER(3)       DEFAULT 30 NOT NULL,
    TELEFONO            VARCHAR2(20),
    EMAIL               VARCHAR2(100),
    ESTADO              CHAR(1)         DEFAULT 'A' NOT NULL,
    CONSTRAINT CHK_MEDICO_ESTADO CHECK (ESTADO IN ('A','I')),
    CONSTRAINT CHK_MEDICO_INTERVALO CHECK (INTERVALO_MINUTOS > 0)
);

/* =========================
   TABLA INTERMEDIA: MEDICO_ESPECIALIDAD
   ========================= */
CREATE TABLE MEDICO_ESPECIALIDAD (
    ID_MEDICO           NUMBER(10)      NOT NULL,
    ID_ESPECIALIDAD     NUMBER(10)      NOT NULL,
    FECHA_ASIGNACION    DATE            DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY (ID_MEDICO, ID_ESPECIALIDAD),
    CONSTRAINT FK_ME_MEDICO FOREIGN KEY (ID_MEDICO)
        REFERENCES MEDICO_TERAPISTA(ID_MEDICO),
    CONSTRAINT FK_ME_ESPECIALIDAD FOREIGN KEY (ID_ESPECIALIDAD)
        REFERENCES ESPECIALIDAD(ID_ESPECIALIDAD)
);

/* =========================
   TABLA: CITA
   ========================= */
CREATE TABLE CITA (
    ID_CITA             NUMBER(10)      PRIMARY KEY,
    ID_PACIENTE         NUMBER(10)      NOT NULL,
    ID_MEDICO           NUMBER(10)      NOT NULL,
    FECHA_CITA          DATE            NOT NULL,
    HORA_CITA           VARCHAR2(5)     NOT NULL,
    ESTADO              VARCHAR2(20)    NOT NULL,
    MOTIVO              VARCHAR2(200),
    OBSERVACIONES       VARCHAR2(200),
    FECHA_REGISTRO      DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_CITA_PACIENTE FOREIGN KEY (ID_PACIENTE)
        REFERENCES PACIENTE(ID_PACIENTE),
    CONSTRAINT FK_CITA_MEDICO FOREIGN KEY (ID_MEDICO)
        REFERENCES MEDICO_TERAPISTA(ID_MEDICO),
    CONSTRAINT CHK_CITA_ESTADO CHECK (ESTADO IN ('PROGRAMADA','CANCELADA','REPROGRAMADA','ATENDIDA'))
);

/* Restricción de negocio:
   un médico no puede tener dos citas en la misma fecha y hora */
CREATE UNIQUE INDEX UK_CITA_MEDICO_FECHA_HORA
ON CITA (ID_MEDICO, FECHA_CITA, HORA_CITA);

/* =========================
   TABLA: HISTORIA_CLINICA
   ========================= */
CREATE TABLE HISTORIA_CLINICA (
    ID_HISTORIA         NUMBER(10)      PRIMARY KEY,
    ID_CITA             NUMBER(10)      NOT NULL UNIQUE,
    FECHA_REGISTRO      DATE            DEFAULT SYSDATE NOT NULL,
    DIAGNOSTICO         VARCHAR2(300),
    PROCEDIMIENTO       VARCHAR2(300),
    OBSERVACIONES       VARCHAR2(400),
    ID_USUARIO_REGISTRA NUMBER(10)      NOT NULL,
    CONSTRAINT FK_HISTORIA_CITA FOREIGN KEY (ID_CITA)
        REFERENCES CITA(ID_CITA),
    CONSTRAINT FK_HISTORIA_USUARIO FOREIGN KEY (ID_USUARIO_REGISTRA)
        REFERENCES USUARIO_SISTEMA(ID_USUARIO)
);

/* =========================
   TABLA: MEDICAMENTO
   ========================= */
CREATE TABLE MEDICAMENTO (
    ID_MEDICAMENTO      NUMBER(10)      PRIMARY KEY,
    NOMBRE              VARCHAR2(100)   NOT NULL UNIQUE,
    PRESENTACION        VARCHAR2(80),
    ESTADO              CHAR(1)         DEFAULT 'A' NOT NULL,
    CONSTRAINT CHK_MEDICAMENTO_ESTADO CHECK (ESTADO IN ('A','I'))
);

/* =========================
   TABLA INTERMEDIA: HISTORIA_MEDICAMENTO
   ========================= */
CREATE TABLE HISTORIA_MEDICAMENTO (
    ID_HISTORIA         NUMBER(10)      NOT NULL,
    ID_MEDICAMENTO      NUMBER(10)      NOT NULL,
    DOSIS               VARCHAR2(50)    NOT NULL,
    FRECUENCIA          VARCHAR2(50)    NOT NULL,
    DURACION_DIAS       NUMBER(4)       NOT NULL,
    PRIMARY KEY (ID_HISTORIA, ID_MEDICAMENTO),
    CONSTRAINT FK_HM_HISTORIA FOREIGN KEY (ID_HISTORIA)
        REFERENCES HISTORIA_CLINICA(ID_HISTORIA),
    CONSTRAINT FK_HM_MEDICAMENTO FOREIGN KEY (ID_MEDICAMENTO)
        REFERENCES MEDICAMENTO(ID_MEDICAMENTO),
    CONSTRAINT CHK_HM_DURACION CHECK (DURACION_DIAS > 0)
);

/* =========================
   TABLA: AUDITORIA
   ========================= */
CREATE TABLE AUDITORIA (
    ID_AUDITORIA        NUMBER(10)      PRIMARY KEY,
    ID_USUARIO          NUMBER(10)      NOT NULL,
    FECHA_EVENTO        DATE            DEFAULT SYSDATE NOT NULL,
    ACCION              VARCHAR2(100)   NOT NULL,
    TABLA_AFECTADA      VARCHAR2(50),
    DESCRIPCION         VARCHAR2(300),
    CONSTRAINT FK_AUDITORIA_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO_SISTEMA(ID_USUARIO)
);

/* =========================
   TABLA: REAGENDAMIENTO
   ========================= */
CREATE TABLE REAGENDAMIENTO (
    ID_REAGENDAMIENTO   NUMBER(10)      PRIMARY KEY,
    ID_CITA             NUMBER(10)      NOT NULL,
    ID_USUARIO          NUMBER(10)      NOT NULL,
    FECHA_ANTERIOR      DATE            NOT NULL,
    HORA_ANTERIOR       VARCHAR2(5)     NOT NULL,
    FECHA_NUEVA         DATE            NOT NULL,
    HORA_NUEVA          VARCHAR2(5)     NOT NULL,
    MOTIVO              VARCHAR2(200),
    FECHA_CAMBIO        DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_REAG_CITA FOREIGN KEY (ID_CITA)
        REFERENCES CITA(ID_CITA),
    CONSTRAINT FK_REAG_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO_SISTEMA(ID_USUARIO)
);
