SET LINESIZE 200
SET PAGESIZE 100
COLUMN TABLE_NAME FORMAT A35

SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME IN (
    'ROL',
    'USUARIO_SISTEMA',
    'PACIENTE',
    'MEDICO_TERAPISTA',
    'ESPECIALIDAD',
    'MEDICO_ESPECIALIDAD',
    'CITA',
    'HISTORIA_CLINICA',
    'MEDICAMENTO',
    'HISTORIA_MEDICAMENTO',
    'AUDITORIA',
    'REAGENDAMIENTO'
)
ORDER BY TABLE_NAME;

EXIT
