SET LINESIZE 200
SET PAGESIZE 100
COLUMN OBJECT_NAME FORMAT A45
COLUMN OBJECT_TYPE FORMAT A20
COLUMN STATUS FORMAT A10

SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM USER_OBJECTS
WHERE OBJECT_TYPE IN ('PACKAGE','PACKAGE BODY','TRIGGER','VIEW','SEQUENCE','INDEX')
ORDER BY OBJECT_TYPE, OBJECT_NAME;

EXIT
