spring.application.name=piedraazul-notification-service
server.port=8082

# BASE DE DATOS - MARIADB
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3308/piedraazul_notifications}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:piedraazul}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:piedraazul}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# SWAGGER / OPENAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.paths-to-match=/api/**

# CONFIGURACIÓN DE CORREO
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# NOTIFICACIONES
notification.mail.enabled=${NOTIFICATION_MAIL_ENABLED:false}
notification.mail.from=${NOTIFICATION_MAIL_FROM:no-reply@piedraazul.com}